# Generated by Django 5.2.8 on 2025-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priorty',
            field=models.CharField(choices=[('1', 'muhim'), ('2', 'uta muhim'), ('3', 'sal muhim')], default=[['1', 'muhim'], ['2', 'uta muhim'], ['3', 'sal muhim']]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
