# Generated by Django 5.2.8 on 2025-11-16 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_priorty_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 11, 23)),
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 11, 16)),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'todo'), ('2', 'in_progres'), ('3', 'review'), ('4', 'done'), ('5', 'canclled')]),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priorty',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'urgent')], default=[['1', 'low'], ['2', 'medium'], ['3', 'high'], ['4', 'urgent']]),
        ),
    ]
