# Generated by Django 5.2.8 on 2025-11-16 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_due_date_task_email_task_start_date_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('todo', 'TODO'), ('in_progres', 'IN_prognez'), ('review', 'Review'), ('done', 'Done'), ('canclled', 'Cancled')], default='todo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
