# Generated by Django 5.2.8 on 2025-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_task_name_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='medium', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priorty',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'urgent')], default=''),
        ),
    ]
