# Generated by Django 5.2.8 on 2025-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_task_description_alter_task_priorty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priorty',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'Heigh'), ('urgent', 'Urgent')], default=''),
        ),
    ]
